scrape_configs:
  - job_name: dcgm_exporter
    static_configs:
      - targets: ["instance_name:9400"]
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        regex: '([^:]+)(:[0-9]+)?'
        replacement: '${1}'
